### ISSUE TITLE
Cannot find module "react" from "web/static/bower_components/react/react-dom"

### ISSUE THREAD

**Issue by ajrob27** [reactjs/react-bower#16]
I'm getting the following error with my Phoenix app that uses Brunch: 
`Cannot find module "react" from "web/static/bower_components/react/react-dom"`

I have the following code: 
```
import React from 'bower_components/react/react';
import ReactDOM from 'bower_components/react/react-dom';
import Map from './components/Map';

ReactDOM.render(<Map />, document.getElementById('map-container'))
```

I can work around the problem my using `React.render()` instead of `ReactDOM.render()`, but I get the depreciation warning for `React.render()`.

My workaround code is: 
```
import React from 'bower_components/react/react';
import Map from './components/Map';
React.render(<Map />, document.getElementById('map-container'))
```

**Comment by stevesuh** [comment]
I'm getting the same behavior but in a Rails 4.2 app.

ReferenceError: ReactDOM is not defined

**Comment by gaearon** [comment]
I just ran `bower install react` in an empty folder with the following `index.html`:

```html
<!DOCTYPE html>
<html>
  <body>
    <div id="container">
    </div>
    <script src="./bower_components/react/react.js"></script>
    <script src="./bower_components/react/react-dom.js"></script>
    <script>
      var ExampleApplication = React.createClass({
        render: function() {
          var elapsed = Math.round(this.props.elapsed  / 100);
          var seconds = elapsed / 10 + (elapsed % 10 ? '' : '.0' );
          var message =
            'React has been successfully running for ' + seconds + ' seconds.';

          return React.DOM.p(null, message);
        }
      });
      var ExampleApplicationFactory = React.createFactory(ExampleApplication);
      var start = new Date().getTime();
      setInterval(function() {
        ReactDOM.render(
          ExampleApplicationFactory({elapsed: new Date().getTime() - start}),
          document.getElementById('container')
        );
      }, 50);
    </script>
  </body>
</html>
```

It ran successfully:

<img width="459" alt="screen shot 2016-03-16 at 18 46 43" src="https://cloud.githubusercontent.com/assets/810438/13824783/7fcc7eba-eba7-11e5-850e-43d7c2306c94.png">

`react.js` and `react-dom.js` in the Bower distributions are UMD builds. Since the example runs fine in the browser, the problem has to be with the way your build tool of choice (e.g. Brunch) handles UMD files. I don’t think there’s anything here that we can fix so I’m closing, but please feel free to suggest a solution if you’re sure this is something we can fix on our side.
